services:
  backend:
    build: ./app/srcs/backend
    container_name: backend_app
    env_file: .env
    ports:
        - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
        - ./database:/database
        - ./app/srcs/backend:/app/srcs/backend
        - ./certs:/certs
    networks:
        - klbq_network

  frontend:
    build: ./app/srcs/frontend
    container_name: frontend_app
    env_file: .env
    ports:
        - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes:
        - ./app/srcs/frontend:/app/srcs/frontend
        - ./certs:/certs
    networks:
        - klbq_network
    depends_on:
        - backend

networks:
    klbq_network:
