services:
  backend:
    build: ./app/srcs/backend
    container_name: backend_app
    env_file: .env
    ports:
        - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
        - backend_db:/database
        - backend_dir:/app/srcs/backend
        - backend_cert:/certs
    networks:
        - klbq_network

  frontend:
    build: ./app/srcs/frontend
    container_name: frontend_app
    env_file: .env
    ports:
        - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes:
        - frontend_dir:/app/srcs/frontend
        - backend_cert:/certs
    networks:
        - klbq_network
    depends_on:
        - backend

networks:
    klbq_network:

volumes:
    backend_db:
    backend_dir:
    backend_cert:
    frontend_dir:

